apiVersion: apps/v1
kind: Deployment
metadata:
  name: brightspace-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brightspace
  template:
    metadata:
      labels:
        app: brightspace
    spec:
      containers:
      - name: brightspace
        image: cdemmer04/brightspace:latest
        ports:
        - containerPort: 80