apiVersion: apps/v1
kind: Deployment
metadata:
  name: bison-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bison
  template:
    metadata:
      labels:
        app: bison
    spec:
      containers:
      - name: bison
        image: cdemmer04/bison:latest
        ports:
        - containerPort: 80